spring:
  application:
    name: authserver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:8084/AUTH_SERVICE
    username: root
    password: test
logging:
  config: /config/logback-spring.xml
  level:
    org.springframework.security: DEBUG
config:
  oauth2:
    default-success-url: "http://localhost:5021/login"
    access-token-validity: 3600
    refresh-token-validity: 18000
    storepass: "=xU2Sk%zv&CXv4Mp"
